global using Libx;
global using Libx.Mvc;
global using Microsoft.AspNetCore.Http;
global using Microsoft.AspNetCore.Mvc;
global using System;
global using System.Linq;
global using System.Collections.Generic;
global using System.Text;
global using System.Threading.Tasks;
global using Microsoft.Extensions.Primitives;
global using static Libx.GlobalThis;
